### ISSUE TITLE
Can't run ghost-phisher.py 

### ISSUE THREAD

**Issue by Skroppo** [savio-code/ghost-phisher#53]
When I try to run

`sudo python3 ghost-phiser.py`

in the /ghost-phisher/Ghost-Phisher directory it returns 
```

Traceback (most recent call last):

  File "ghost.py", line 15, in <module>

    from gui import *

  File "/home/[user]/git/ghost-phisher/Ghost-Phisher/gui/ghost_phisher.py", line 729

    essid = str(self.access_name_edit.text())

                                            ^

TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by rohittp0** [comment]
I am getting the exact same problem running Python 3.7.6 and Kali 2020.1 please help

**Comment by cherrera0001** [comment]
I'm install other version but the code return "issues" :/

I proof install # pip install PyQt5 (of Python3.8) 

- Kali 2020.1

**Comment by hellothere9898** [comment]
How do I proof install and run it??
